
select * from customer limit 3;

-- Q1 what is the the total revenue generated by male vs female ?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender;
	
-- Q2 what is the customer that have discoutn applied and spend more the average purchase amount
select customer_id , purchase_amount
from customer
where discount_applied = "Yes" and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3 with are the top 5 product with the high average review ratings
select item_purchased , round(avg(review_rating),2) as "Customer Product Ratings"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4 comparer the average Purchase Amounts between Standard and express shiping 
select shipping_type, AVG(purchase_amount)
from customer
where shipping_type in ('Express', 'Standard')
group by shipping_type ;

-- Q5 DO subscrib customer spned more ? compare average spend and total revenue between subscriber and non sunscribere
select subscription_status, avg(purchase_amount) as "average Customer Revenue", sum(purchase_amount) as "Total Costumer Revenue"
from customer
group by subscription_status;
 
-- Q6 which 5 products have the highest percentage of purchase with discounts applied ?
select item_purchased , round(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 end)/ count(*)* 100,2) as discount_rate 
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7 segment customer into new , Returning , and loyal based on their total number of previeus purchase, and show the count of each segments.
with customer_type as (
select customer_id, previous_purchases,
CASE 
 WHEN previous_purchases = 1 THEN 'New'
 WHEN previous_purchases between 2 and 3 THEN 'Returning' ELSE 'Loyal'
 END AS customer_segment
from customer
)

select customer_segment, count(customer_id)
from customer_type
group by customer_segment; 

-- Q8 What are the 3 most purchased product within each category ? 
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
select item_rank, category,item_purchased , total_orders 
from item_counts
where item_rank <=3;

-- Q9 are customers who are repeat buyers (more 5 previeus purchases ) also likely to subscribes ?
select subscription_status,
count(customer_id) as repeat_buyers
from customer 
where previous_purchases > 5 
group by subscription_status;

-- Q10 what is the revenue contribution of each age group ? 
select age,
sum(purchase_amount) as total_revenue 
from customer
group by age
order by total_revenue desc;

	




 

